import { useState, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Button, Col } from 'react-bootstrap'
// import { Parallax, ParallaxLayer } from '@react-spring/parallax'
import { Parallax, ParallaxBanner } from 'react-scroll-parallax'
import Typed from 'react-typed'

import styles from '../styles/Home.module.css'
import Divider from '../components/Divider'
import WordCloud from '../components/WordCloud'

const HeadBanner = () => {
  const background = {
    image: '/starry-background-1.jpg',
    translateY: [0, 50],
    opacity: [1, 0.3],
    scale: [1.05, 1, 'easeOutCubic'],
    shouldAlwaysCompleteAnimation: true,
  };

  const headline = {
    translateY: [0, 30],
    scale: [1, 1.05, 'easeOutCubic'],
    shouldAlwaysCompleteAnimation: true,
    expanded: false,
    children: (
      <div className={styles.banner} style={{ 
        // transform: `translateY(-${offsetY * 1.2}px)`,
        height: `${500}px`,
        // backgroundColor: `rgba(0, 0, 0, ${offsetY / 500})`,
        // backgroundColor: `rgba(255, 255, 255, ${offsetY / screenHeight})`,
      }}>
        <h1 className={styles.title}>
          Hi, I'm <Link href="/contact" style={{ color: "#E6BCCD" }}>Renault</Link>.
          <p className={styles.description}>
            I'm a 
            <code className={styles.code}>
              <Typed 
                strings={[
                  'Software Developer',
                  'Product Designer',
                  'Embedded Systems Engineer',
                  'Graphic Designer',
                ]}
                typeSpeed={120}
                backSpeed={60}
                loop
              />
            </code>
            .
          </p>
        </h1>
      </div>
    ),
  };

  const gradientOverlay = {
    opacity: [0, 1],
    shouldAlwaysCompleteAnimation: true,
    expanded: false,
    children: (
      <div className="absolute inset-0 bg-gradient-to-t from-gray-900 to-purple-900" />
    ),
  };

  return (
    <ParallaxBanner
      layers={[background, headline, gradientOverlay]}
      // className="aspect-[2/1] bg-gray-900"
      // style={{
      //   height: 500,
      //   width: "100%"
      // }}
      className={styles.headBanner}
    />
  );
}

export default function Home() {
  const [offsetY, setOffsetY] = useState(0);
  // let screenHeight = 0;

  const handleScroll = () => {
    setOffsetY(window.pageYOffset);
  }

  useEffect(() => {
    // screenHeight = window.innerHeight;
    window.addEventListener('scroll', handleScroll);
    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);
  
  return (
    <>
      <Head>
        <title>Renault Luk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <HeadBanner /> */}
      <div className={styles.container}>
        {/* <main className={styles.main}> */}
        <main style={{ width: "80%", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center" }}>
          
          <div className={styles.banner} style={{ 
            // transform: `translateY(-${offsetY * 1.2}px)`,
            height: `${500}px`,
            // backgroundColor: `rgba(0, 0, 0, ${offsetY / 500})`,
            // backgroundColor: `rgba(255, 255, 255, ${offsetY / screenHeight})`,
          }}>
            <h1 className={styles.title}>
              Hi, I'm <a href="" style={{ color: "#E6BCCD" }}>Renault</a>.
              <p className={styles.description}>
                I'm a 
                <code className={styles.code}>
                  <Typed 
                    strings={[
                      'Software Developer',
                      'Product Designer',
                      'Embedded Systems Engineer',
                      'Graphic Designer',
                    ]}
                    typeSpeed={120}
                    backSpeed={60}
                    loop
                  />
                </code>
                .
              </p>
            </h1>
          </div>
          
            <div className="d-flex flex-column flex-sm-row-reverse align-items-center justify-content-around">

              <div style={{ 
                position: "relative", 
                // left: "50%",
              }}>
                <Parallax
                  rotate={[0,360]}
                  // startScroll={200}
                  endScroll={1000}
                  style={{ 
                    width: 200,
                    height: 200,
                    display: "flex",
                    justifyContent: "center",
                    alignItems: "center",
                  }}
                >
                    <img
                      src="/profile_ring.svg" 
                      style={{ flex: 1 }}
                    />
                </Parallax>
                <img 
                      src="/Profile.JPG" 
                      width={150}
                      height={150}
                      style={{
                        borderRadius: 150,
                        objectFit: "cover",
                        position: "absolute",
                        top: 25,
                        left: 25,
                      }} 
                    />
                </div>
              <Parallax
                  rotateX={[-90, 0, 'easeOutExpo']}
                  startScroll={200}
                  endScroll={700}
              >
                  <Col style={{ 
                    padding: 16, 
                    // width: "50%" 
                  }}
                    xs={12} sm={8}
                  >
                      <h4>About Me</h4>
                      <span>Hi! My name is Renault, and I am a Software Developer based in Hong Kong, armed with Embedded Systems Engineering, UI/UX Design, and Product Design skills. I’m a problem solver, a team player, and a curious and inquisitive learner.</span>
                  </Col>
              </Parallax>
            </div>

          <div className="d-flex flex-column flex-sm-row align-items-center" style={{ marginTop: 20, marginBottom: 20, }}>
            <WordCloud 
              wordList={[
                "React.js",
                "Next.js",
                "React Native",
                "CSS",
                "Bootstrap",
                "Electron",
                "Firebase",
                "Python",
                "Pandas",
                "Tensorflow",
                "C++",
                "Java",
                "Kotlin",
                "XML",
                "REST",
                "Github",
              ]}
            />

            <Parallax
                rotateX={[-90, 0, 'easeOutExpo']}
                startScroll={500}
                endScroll={1000}
            >
                <div style={{ padding: 16 }}>
                    <h4>Software Development</h4>
                    <span>An aspiring full stack developer at heart, my focus is on creating frontends on websites, desktop and mobile applications; and have experience with devising backend logic and database management; as well as adding machine learning.</span>
                </div>
            </Parallax>
          </div>

          <div className="d-flex flex-column flex-sm-row-reverse align-items-center">

          <div
            style={{
              position: "relative",
              overflow: "hidden",
              height: 258,
            }}
          >
              <Parallax
                translateY={[200, 0]}
                startScroll={0}
                endScroll={700}
              >
                <div
                  style={{
                    width: 200,
                    height: 250,
                    borderRadius: 8,
                    borderColor: "#BBBBBD",
                    borderWidth: 1,
                    backgroundColor: "rgba(255,255,255,0.15)",
                  }}
                />
              </Parallax>
          </div>
          <Parallax
                rotateX={[-90, 0, 'easeOutExpo']}
                startScroll={500}
                endScroll={1000}
            >
                <div style={{ padding: 16 }}>
                    <h4>UI/UX Design</h4>
                    <span>Using interaction design principles, I create designs that minimise interaction cost, and account for product’s context of usage for the best user experience.</span>
                </div>
            </Parallax>
          </div>

            <Parallax
                rotateX={[-90, 0, 'easeOutExpo']}
                startScroll={500}
                endScroll={1000}
            >
                <div style={{ padding: 16 }}>
                    <h4>Embedded Systems Engineering</h4>
                    <span>From sourcing components, to designing circuits and PCBs, and developing embedded software, I am interested in creating embedded devices and IoT systems.</span>
                </div>
            </Parallax>

            <Parallax
                rotateX={[-90, 0, 'easeOutExpo']}
                startScroll={500}
                endScroll={1000}
            >
                <div style={{ padding: 16 }}>
                    <h4>Product Design</h4>
                    <span>Armed with design thinking skills, I enjoy identifying existing problems and user needs, creating concept sketches, and bringing the product into fruition with the aid of CAD, as well as my technical knowledge with software, hardware and design principles.</span>
                </div>
            </Parallax>

          {/* <div className={styles.banner} 
          style={{
            // transform: `translateY(-${offsetY * 0.5}px)`,
            height: `${500}px`,
          }}
          >
            <h2>Projects</h2>
            <p>Check out some of my projects.</p>
            <Button variant="primary" href="/work" style={{ width: "fit-content" }}>
              Projects &rarr;
            </Button>
          </div>

          <div className={styles.banner} 
          style={{
            // transform: `translateY(-${offsetY * 0.7}px)`,
            height: `${500}px`,
          }}
          >
            <h2>Contact Me</h2>
            <p>Find me through different channels!</p>
            <Button variant="primary" href="/work" style={{ width: "fit-content" }}>
              Contact &rarr;
            </Button>
          </div> */}
        </main>
      </div>
    </>
  )
}
